### ISSUE TITLE
ZF issue [needs to be verified and addressed]

### ISSUE THREAD

**Issue by kalpaj12** [PawanKartikS/ASE#10]
```
MOV AX , -1
ADD AX , 0
```

ZF gets set in the above instruction sequence.

**Comment by PawanKartikS** [comment]
Both #10 and #9 are related. The conversion of -ve numbers to hex and vice vera needs to be looked upon. Will close these issues when the conversion is taken care of. Or see if you can fix it and send a PR. Will then merge it into the master.

**Comment by kalpaj12** [comment]
I guess, all ZF related issues are fixed after commit: 298549ddcd5d647d7ce1c4fed5363615d6b5c9b4

Check and close issue accordingly.
