### ISSUE TITLE
To be addressed ASAP

### ISSUE THREAD

**Issue by kalpaj12** [PawanKartikS/ASE#11]
```
MOV AX, -10
ADD AX, -10
```

Check why this causes OF to get set.

Also 
```
MOV AX, -10
MOV AX, -20
```
sets DX for no reason.

**Comment by PawanKartikS** [comment]
Refer to my comment on #10 .

**Comment by kalpaj12** [comment]
Once I try fixing #9 and #10, I will have to check for, whether this issue gets resolved or not.

**Comment by PawanKartikS** [comment]
Sure. I can give you some info about where things are going wrong.

ASE uses `strtol` to convert between int and hex formats. When the parser reads the negative number, it calls `strtol` to convert to hex (all the numbers are stored internally in hex format). This is where the problem is.

**Comment by kalpaj12** [comment]
Fixed the negative number issue, **accept all the PR's.** 

I couldn't figure out why DX is getting set for the below code.
```
MOV AX, -10
MOV AX, -20
```

or

```
MOV AX, -10
MOV AX, -20
```

**Comment by PawanKartikS** [comment]
Could you please explain how your PR fixes this issue?

**Comment by kalpaj12** [comment]
Description of PR is provided in the PR itself.

**Comment by PawanKartikS** [comment]
Next commit should fix the issue with DX.

**Comment by PawanKartikS** [comment]
Latest commit fixes this issue. Closing.
