### ISSUE TITLE
Debug mode and stack

### ISSUE THREAD

**Issue by kalpaj12** [PawanKartikS/ASE#22]
When debug mode is enabled, final stack result in inconsistent.

```
MOV AX, 10
PUSH AX
```

Run the above code with and without debug and see the stack.

**Comment by PawanKartikS** [comment]
This is a known issue. It is marked as pending in my todo list. There's some issue with stack pointer I guess.

**Comment by PawanKartikS** [comment]
737d73c fixes this.
