### ISSUE TITLE
Issue with Jump

### ISSUE THREAD

**Issue by kalpaj12** [PawanKartikS/ASE#29]
```
MOV CX, 5
MOV AX, 1
L1: MUL CX
STC
JC L1
```

Tried to create an infinite loop, looks like JC looks for lables only below them.

Expected output:
When on `JC L1`, jump to `L1: MUL CX`

Real outcome:
`Emulator halted due to an error in line` XX. `State preserved.`

**Comment by PawanKartikS** [comment]
Label for jump statements as of now must be specified after the jump instruction. There is a fix for this limitation that should be coming soon.

**Comment by PawanKartikS** [comment]
Upcoming commit fixes this issue. If you run into any problem, open a new issue.
