### ISSUE TITLE
Overflow flag issue

### ISSUE THREAD

**Issue by kalpaj12** [PawanKartikS/ASE#5]
```
MOV AX, 65535
MOV BX, 1
ADD AX, BX
```
Expected overflow flag to get set.

Result is otherwise.

**Comment by PawanKartikS** [comment]
Yes, I'm aware of this issue. The math operations are not fully implemented and will be done when the logical instruction set is ready.

**Comment by PawanKartikS** [comment]
Commit 811a60d fixes the issue, but the change of OF flag remains un-affected for other operations. For those operations, you could open a new issue.
